/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.devworks.view;

import br.com.devworks.dao.ClientesDAO;
import br.com.devworks.dao.FuncionariosDAO;
import br.com.devworks.model.Clientes;
import br.com.devworks.model.Funcionarios;
import br.com.devworks.model.utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz
 */
public class telaFuncionarios extends javax.swing.JFrame {

    //listando dados da tabela
    public void listar(){
    
    FuncionariosDAO dao = new FuncionariosDAO();
    List<Funcionarios> lista = dao.listarFuncionarios();
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeFuncionarios.getModel();
    dados.setNumRows(0);
    
    
    for(Funcionarios c: lista){
        
        dados.addRow(new Object[]{
            c.getId(),
            c.getNome(),
            c.getRg(),
            c.getCpf(),
            c.getEmail(),
            c.getSenha(),
            c.getCargo(),
            c.getNivel_acesso(),
            c.getTelefone(),
            c.getCelular(),
            c.getCep(),
            c.getEndereco(),
            c.getNumero(),
            c.getComplemento(),
            c.getBairro(),
            c.getCidade(),
            c.getUf()
                
            
                
        });
    
    }
    
        
    
    }
    public telaFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelDaTabelaClientes = new javax.swing.JTabbedPane();
        painelDadosPessoais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoDados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeDados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailDados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCelularDados = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefonedados = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCepDados = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEnderecoDados = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBairroDados = new javax.swing.JTextField();
        txtCidadeDados = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboUfDados = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtRgDados = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCpfDados = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNumeroDados = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtComplementoDados = new javax.swing.JTextField();
        btnPesquisaNomeDadosPessoais = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtSenhaFuncionario = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCargoFuncionario = new javax.swing.JTextField();
        comboNivelAcesso = new javax.swing.JComboBox<>();
        painelConsultaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeFuncionarios = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtNomeConsultaFuncionario = new javax.swing.JTextField();
        btnPesquisaCliente = new javax.swing.JToggleButton();
        btnSalvarCadFuncio = new javax.swing.JButton();
        btnNovoCadCli = new javax.swing.JButton();
        btnExcluirCadFuncio = new javax.swing.JButton();
        btnEditarCadFuncio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Funcionários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Codigo: ");

        txtCodigoDados.setEditable(false);
        txtCodigoDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCodigoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDadosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        txtNomeDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomeDados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeDadosKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        txtEmailDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmailDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailDadosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Celular:");

        try {
            txtCelularDados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Telefone fixo");

        try {
            txtTelefonedados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefonedados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("CEP: ");

        txtCepDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCepDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepDadosActionPerformed(evt);
            }
        });
        txtCepDados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCepDadosKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Endereço:");

        txtEnderecoDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEnderecoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoDadosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Bairro:");

        txtBairroDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBairroDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroDadosActionPerformed(evt);
            }
        });

        txtCidadeDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCidadeDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeDadosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Cidade:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("UF:");

        comboUfDados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("RG:");

        try {
            txtRgDados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("CPF:");

        try {
            txtCpfDados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Número:");

        txtNumeroDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNumeroDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDadosActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Complemento:");

        txtComplementoDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtComplementoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoDadosActionPerformed(evt);
            }
        });

        btnPesquisaNomeDadosPessoais.setText("Pesquisar");
        btnPesquisaNomeDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNomeDadosPessoaisActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Senha:");

        txtSenhaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaFuncionarioActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Nível de acesso:");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Cargo:");

        txtCargoFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCargoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoFuncionarioActionPerformed(evt);
            }
        });

        comboNivelAcesso.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        comboNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador", "Administrador" }));

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeDados))
                            .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmailDados, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodigoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelularDados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefonedados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPesquisaNomeDadosPessoais))
                        .addContainerGap())
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBairroDados, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCepDados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(txtEnderecoDados)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboUfDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(txtNumeroDados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtComplementoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(comboNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRgDados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfDados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(162, Short.MAX_VALUE))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidadeDados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaNomeDadosPessoais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCelularDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonedados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCepDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnderecoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(comboUfDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtCpfDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtComplementoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairroDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtRgDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(comboNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        painelDaTabelaClientes.addTab("Dados pessoais", painelDadosPessoais);

        tabelaDeFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "Email", "Senha", "Cargo", "Nível", "Telefone", "Celular", "CEP", "Endereço", "Número", "Comp.", "Bairro", "Cidade", "UF"
            }
        ));
        tabelaDeFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDeFuncionarios);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Nome:");

        txtNomeConsultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConsultaFuncionarioActionPerformed(evt);
            }
        });
        txtNomeConsultaFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeConsultaFuncionarioKeyPressed(evt);
            }
        });

        btnPesquisaCliente.setText("Pesquisar");
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaClientesLayout = new javax.swing.GroupLayout(painelConsultaClientes);
        painelConsultaClientes.setLayout(painelConsultaClientesLayout);
        painelConsultaClientesLayout.setHorizontalGroup(
            painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsultaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(888, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelConsultaClientesLayout.setVerticalGroup(
            painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeConsultaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisaCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDaTabelaClientes.addTab("Consulta de Funcionários", painelConsultaClientes);

        btnSalvarCadFuncio.setText("SALVAR");
        btnSalvarCadFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadFuncioActionPerformed(evt);
            }
        });

        btnNovoCadCli.setText("NOVO");
        btnNovoCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadCliActionPerformed(evt);
            }
        });

        btnExcluirCadFuncio.setText("EXCLUIR");
        btnExcluirCadFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadFuncioActionPerformed(evt);
            }
        });

        btnEditarCadFuncio.setText("EDITAR");
        btnEditarCadFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadFuncioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDaTabelaClientes)
            .addGroup(layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(btnNovoCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarCadFuncio)
                .addGap(18, 18, 18)
                .addComponent(btnEditarCadFuncio)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirCadFuncio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(painelDaTabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCadFuncio)
                    .addComponent(btnExcluirCadFuncio)
                    .addComponent(btnSalvarCadFuncio)
                    .addComponent(btnNovoCadCli))
                .addGap(37, 37, 37))
        );

        setSize(new java.awt.Dimension(1400, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDadosActionPerformed

    private void txtEmailDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailDadosActionPerformed

    private void txtEnderecoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoDadosActionPerformed

    private void txtBairroDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroDadosActionPerformed

    private void txtCidadeDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeDadosActionPerformed

    private void txtNomeConsultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaFuncionarioActionPerformed

    private void txtNumeroDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDadosActionPerformed

    private void txtComplementoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoDadosActionPerformed

    private void btnSalvarCadFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadFuncioActionPerformed
        // TODO add your handling code here:

        try {

            Funcionarios obj = new Funcionarios();
            obj.setNome(txtNomeDados.getText());
            obj.setRg(txtRgDados.getText());
            obj.setCpf(txtCpfDados.getText());
            obj.setEmail(txtEmailDados.getText());
            obj.setSenha(txtSenhaFuncionario.getText());
            obj.setCargo(txtCargoFuncionario.getText());
            obj.setNivel_acesso((String) comboNivelAcesso.getSelectedItem());
            obj.setTelefone(txtTelefonedados.getText());
            obj.setCelular(txtCelularDados.getText());
            obj.setCep(txtCepDados.getText());
            obj.setEndereco(txtEnderecoDados.getText());
            obj.setNumero(Integer.parseInt(txtNumeroDados.getText()));
            obj.setComplemento(txtComplementoDados.getText());
            obj.setBairro(txtBairroDados.getText());
            obj.setCidade(txtCidadeDados.getText());
            obj.setUf(comboUfDados.getSelectedItem().toString());
            
            FuncionariosDAO dao = new FuncionariosDAO();
            dao.cadastrarFuncionarios(obj);
                        new utilitarios().LimpaTela(painelDadosPessoais);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }


    }//GEN-LAST:event_btnSalvarCadFuncioActionPerformed

    private void btnNovoCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoCadCliActionPerformed

    private void btnExcluirCadFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadFuncioActionPerformed
                try {
                  Clientes obj = new Clientes();

                 obj.setId(Integer.parseInt(txtCodigoDados.getText()));
                      ClientesDAO dao = new ClientesDAO();
                      dao.excluirCliente(obj);
            new utilitarios().LimpaTela(painelDadosPessoais);

            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnExcluirCadFuncioActionPerformed

    private void btnEditarCadFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadFuncioActionPerformed
        // TODO add your handling code here:
        

        try {

            Funcionarios obj = new Funcionarios();
            obj.setNome(txtNomeDados.getText());
            obj.setRg(txtRgDados.getText());
            obj.setCpf(txtCpfDados.getText());
            obj.setEmail(txtEmailDados.getText());
            obj.setSenha(txtSenhaFuncionario.getText());
            obj.setCargo(txtCargoFuncionario.getText());
            obj.setNivel_acesso((String) comboNivelAcesso.getSelectedItem());
            obj.setTelefone(txtTelefonedados.getText());
            obj.setCelular(txtCelularDados.getText());
            obj.setCep(txtCepDados.getText());
            obj.setEndereco(txtEnderecoDados.getText());
            obj.setNumero(Integer.parseInt(txtNumeroDados.getText()));
            obj.setComplemento(txtComplementoDados.getText());
            obj.setBairro(txtBairroDados.getText());
            obj.setCidade(txtCidadeDados.getText());
            obj.setUf(comboUfDados.getSelectedItem().toString());
            obj.setId(Integer.parseInt(txtCodigoDados.getText()));
            
            FuncionariosDAO dao = new FuncionariosDAO();
            dao.alterarFuncionario(obj);
            new utilitarios().LimpaTela(painelDadosPessoais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_btnEditarCadFuncioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       ///caregar a lista
       listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void tabelaDeFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeFuncionariosMouseClicked
        // passar dados da tabela para o painel de Dados Pessoais
        painelDaTabelaClientes.setSelectedIndex(0);
        txtCodigoDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 0).toString());
        
        txtNomeDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 1).toString());
        
        txtRgDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 2).toString());
        
        txtCpfDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 3).toString());
        
        txtEmailDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 4).toString());
        
          txtSenhaFuncionario.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 5).toString());
          
            txtCargoFuncionario.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 6).toString());
            
              comboNivelAcesso.setSelectedItem(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 7).toString());
              
        txtTelefonedados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 8).toString());
        
        txtCelularDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 9).toString());
        
        txtCepDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 10).toString());
        
        txtEnderecoDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 11).toString());
        
        txtNumeroDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 12).toString());
        
        txtComplementoDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 13).toString());
        
        txtBairroDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 14).toString());
        
        txtCidadeDados.setText(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 15).toString());
        
        comboUfDados.setSelectedItem(tabelaDeFuncionarios.getValueAt(tabelaDeFuncionarios
                .getSelectedRow(), 16).toString());
        
        
    }//GEN-LAST:event_tabelaDeFuncionariosMouseClicked

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        // Botao pesquisar na tabela de clientes
        
        String nome = "%"+txtNomeConsultaFuncionario.getText()+"%";
         ClientesDAO dao = new ClientesDAO();
    List<Clientes> lista = dao.buscaClientePorNome(nome);
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeFuncionarios.getModel();
    dados.setNumRows(0);
    
    
    for(Clientes c: lista){
        
        dados.addRow(new Object[]{
            c.getId(),
            c.getNome(),
            c.getRg(),
            c.getCpf(),
            c.getEmail(),
            c.getTelefone(),
            c.getCelular(),
            c.getCep(),
            c.getEndereco(),
            c.getNumero(),
            c.getComplemento(),
            c.getBairro(),
            c.getCidade(),
            c.getUf()
                
            
                
        });
    }
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void txtNomeConsultaFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeConsultaFuncionarioKeyPressed
        // Pesquisa enquanto digita
         String nome = "%"+txtNomeConsultaFuncionario.getText()+"%";
         FuncionariosDAO dao = new FuncionariosDAO();
    List<Funcionarios> lista = dao.buscaFuncionarioPorNome(nome);
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeFuncionarios.getModel();
    dados.setNumRows(0);
    
    
    for(Clientes c: lista){
        
        dados.addRow(new Object[]{
            c.getId(),
            c.getNome(),
            c.getRg(),
            c.getCpf(),
            c.getEmail(),
            c.getTelefone(),
            c.getCelular(),
            c.getCep(),
            c.getEndereco(),
            c.getNumero(),
            c.getComplemento(),
            c.getBairro(),
            c.getCidade(),
            c.getUf()
                
            
                
        });
    }
    }//GEN-LAST:event_txtNomeConsultaFuncionarioKeyPressed

    private void btnPesquisaNomeDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNomeDadosPessoaisActionPerformed
        // Pesquisar na tela dados pessoais
        try {
            String nome = txtNomeDados.getText();
            Clientes obj = new Clientes();
            ClientesDAO dao = new ClientesDAO();
            
            obj = dao.consultaPorNome(nome);
            if(obj.getNome() != null){
            txtCodigoDados.setText(String.valueOf(obj.getId()));
            
               txtNomeDados.setText(obj.getNome());
        txtRgDados.setText(obj.getRg());
        txtCpfDados.setText(obj.getCpf());
        txtEmailDados.setText(obj.getEmail());
        txtTelefonedados.setText(obj.getTelefone());
        txtCelularDados.setText(obj.getCelular());
        txtCepDados.setText(obj.getCep());
        txtEnderecoDados.setText(obj.getEndereco());
        txtNumeroDados.setText(Integer.toString(obj.getNumero()));
        txtComplementoDados.setText(obj.getComplemento());
        txtBairroDados.setText(obj.getBairro());
        txtCidadeDados.setText(obj.getCidade());
        comboUfDados.setSelectedItem(obj.getUf());
            }else{
            JOptionPane.showMessageDialog(null, "CLIENTE NÃO ENCONTRADO");
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           
    }//GEN-LAST:event_btnPesquisaNomeDadosPessoaisActionPerformed

    private void txtCepDadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepDadosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Clientes obj =  new Clientes();
         ClientesDAO dao = new ClientesDAO();
         obj = dao.buscaCep(txtCepDados.getText());
         
         txtEnderecoDados.setText(obj.getEndereco());
         txtBairroDados.setText(obj.getBairro());
         txtCidadeDados.setText(obj.getCidade());
         comboUfDados.setSelectedItem(obj.getUf());               
        
         
     }
        
        
    }//GEN-LAST:event_txtCepDadosKeyPressed

    private void txtCepDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepDadosActionPerformed

    private void txtNomeDadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeDadosKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        try {
            String nome = txtNomeDados.getText();
            Clientes obj = new Clientes();
            ClientesDAO dao = new ClientesDAO();
            
            obj = dao.consultaPorNome(nome);
            if(obj.getNome() != null){
            txtCodigoDados.setText(String.valueOf(obj.getId()));
            
               txtNomeDados.setText(obj.getNome());
        txtRgDados.setText(obj.getRg());
        txtCpfDados.setText(obj.getCpf());
        txtEmailDados.setText(obj.getEmail());
        txtTelefonedados.setText(obj.getTelefone());
        txtCelularDados.setText(obj.getCelular());
        txtCepDados.setText(obj.getCep());
        txtEnderecoDados.setText(obj.getEndereco());
        txtNumeroDados.setText(Integer.toString(obj.getNumero()));
        txtComplementoDados.setText(obj.getComplemento());
        txtBairroDados.setText(obj.getBairro());
        txtCidadeDados.setText(obj.getCidade());
        comboUfDados.setSelectedItem(obj.getUf());
            }else{
            JOptionPane.showMessageDialog(null, "CLIENTE NÃO ENCONTRADO");
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
       }
    }//GEN-LAST:event_txtNomeDadosKeyPressed

    private void txtCargoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoFuncionarioActionPerformed

    private void txtSenhaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCadFuncio;
    private javax.swing.JButton btnExcluirCadFuncio;
    private javax.swing.JButton btnNovoCadCli;
    private javax.swing.JToggleButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaNomeDadosPessoais;
    private javax.swing.JButton btnSalvarCadFuncio;
    private javax.swing.JComboBox<String> comboNivelAcesso;
    private javax.swing.JComboBox<String> comboUfDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelConsultaClientes;
    private javax.swing.JTabbedPane painelDaTabelaClientes;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JTable tabelaDeFuncionarios;
    private javax.swing.JTextField txtBairroDados;
    private javax.swing.JTextField txtCargoFuncionario;
    private javax.swing.JFormattedTextField txtCelularDados;
    private javax.swing.JFormattedTextField txtCepDados;
    private javax.swing.JTextField txtCidadeDados;
    private javax.swing.JTextField txtCodigoDados;
    private javax.swing.JTextField txtComplementoDados;
    private javax.swing.JFormattedTextField txtCpfDados;
    private javax.swing.JTextField txtEmailDados;
    private javax.swing.JTextField txtEnderecoDados;
    private javax.swing.JTextField txtNomeConsultaFuncionario;
    private javax.swing.JTextField txtNomeDados;
    private javax.swing.JTextField txtNumeroDados;
    private javax.swing.JFormattedTextField txtRgDados;
    private javax.swing.JPasswordField txtSenhaFuncionario;
    private javax.swing.JFormattedTextField txtTelefonedados;
    // End of variables declaration//GEN-END:variables
}
